apiVersion: v1
kind: Namespace
metadata:
  name: simple-http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: simple-http
  name: simple-http-deployment
  labels:
    app: simple-http
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: simple-http
  template:
    metadata:
      labels:
        app: simple-http
    spec:
      containers:
      - image: smdeeg/simple-http:go-buildpack
        name: simple-http
---
apiVersion: v1
kind: Service
metadata:
  namespace: simple-http
  name: simple-http-lb
spec:
  ports:
    - name: simple-http-svc-ports
      port: 80
      targetPort: 8090
      protocol: TCP
  selector:
    app: simple-http
  type: LoadBalancer
status:
  loadBalancer: {}
